import { test, expect, type Page } from '@playwright/test'
import { createHash } from 'node:crypto'
import { mkdir, open, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { extract } from 'tar-stream'

async function tarContents(path: string) {
  const archive = extract(), entries = new Map<string, Buffer>()
  const reading = (async () => { for await (const entry of archive) {
    const chunks: Buffer[] = []; for await (const chunk of entry) chunks.push(chunk)
    entries.set(entry.header.name, Buffer.concat(chunks))
  } })()
  archive.end(await readFile(path)); await reading
  return entries
}

async function openLocalFolder(page: Page, folder = 'Team documents') {
  await page.getByRole('navigation', { name: 'Main', exact: true }).getByRole('button', { name: 'My files', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'My files', exact: true })).toBeVisible()
  await page.getByRole('list', { name: 'Storage targets', exact: true }).getByRole('button', { name: 'Local', exact: true }).click()
  if (folder) await page.getByRole('button', { name: folder, exact: true }).click()
}

test('setup, file operations, worker hashing, reload resume, scoped users, and mobile layout', async ({ page, context }, testInfo) => {
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Make yourself at home.' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('setup.png'), fullPage: true })
  await page.getByLabel('Workspace name').fill('Filebrowser')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByLabel('Read only', { exact: true })).toBeChecked()
  await page.getByLabel('Read only', { exact: true }).uncheck()
  await page.getByLabel('Root directory').fill(join(process.env.FB_E2E_ROOT!, 'files'))
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByLabel('Username', { exact: true }).fill('admin')
  const strength = page.locator('#password-strength')
  for (const password of ['123456123456', '123456123456123456123456', 'passwordpassword', 'abcdefghijkl']) {
    await page.getByLabel('Password', { exact: true }).fill(password)
    await expect(strength.locator('small')).toHaveText('Very weak')
    await expect(strength.locator('.strength-feedback')).not.toBeEmpty()
  }
  await page.getByLabel('Password', { exact: true }).fill('qwertyuiop12')
  await expect(strength.locator('small')).toHaveText('Weak')
  await page.getByLabel('Password', { exact: true }).fill('vR7!jQ2#')
  await expect(strength.locator('small')).toHaveText('Too short')
  await page.getByLabel('Password', { exact: true }).fill('vR7!jQ2#tL9$wN5@')
  await expect(strength.locator('small')).toHaveText('Strong')
  await page.getByLabel('Username', { exact: true }).fill('vR7!jQ2')
  await page.getByLabel('Password', { exact: true }).fill('vR7!jQ2vR7!jQ2')
  await expect(strength.locator('small')).toHaveText('Weak')
  await page.getByLabel('Username', { exact: true }).fill('admin')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByLabel('Password', { exact: true }).fill('123456123456')
  await expect(strength.locator('small')).toHaveText('Very weak')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const card = await page.locator('.auth-card').boundingBox()
  expect(card!.x).toBeGreaterThanOrEqual(0)
  expect(card!.x + card!.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: testInfo.outputPath('weak-password-mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 980 })
  await page.getByLabel('Password', { exact: true }).fill('browser-test-password-123')
  await page.getByLabel('Confirm password').fill('browser-test-password-123')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByLabel('Read only', { exact: true }).check()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.locator('.review-list')).toContainText('Disabled · read only')
  await expect(page.locator('.review-list')).not.toContainText('Resumable, SHA-256 verified')
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByLabel('Read only', { exact: true }).uncheck()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Create workspace', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'My files' })).toBeVisible()
  await expect(page.getByLabel('Storage target', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'New folder', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Upload files', exact: true })).toHaveCount(0)
  const headers = { 'x-filebrowser-request': '1' }
  await mkdir(join(process.env.FB_E2E_ROOT!, 'archive'), { recursive: true })
  await writeFile(join(process.env.FB_E2E_ROOT!, 'archive', 'archive-only.txt'), 'Archive target content')
  const archiveTarget = { name: 'Archive', connection: { type: 'local', root: join(process.env.FB_E2E_ROOT!, 'archive') }, enabled: true, readOnly: true }
  expect((await context.request.post('/api/admin/targets', { headers, data: archiveTarget })).status()).toBe(201)
  const disabled = await context.request.post('/api/admin/targets', { headers, data: { ...archiveTarget, name: 'Disabled', enabled: false, connection: { type: 'local', root: join(process.env.FB_E2E_ROOT!, 'disabled') } } })
  expect(disabled.status()).toBe(201)
  const disabledId = (await disabled.json()).id
  await page.getByRole('button', { name: 'Refresh targets', exact: true }).click()
  const targetList = page.getByRole('list', { name: 'Storage targets', exact: true })
  await expect(targetList.getByRole('button')).toHaveCount(2)
  await expect(targetList.getByRole('button', { name: 'Disabled', exact: true })).toHaveCount(0)
  await page.getByLabel('Search targets', { exact: true }).fill('arch')
  await expect(targetList.getByRole('button')).toHaveCount(1)
  await page.getByLabel('Search targets', { exact: true }).fill('missing')
  await expect(page.getByRole('heading', { name: 'No matching targets' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear filter' }).click()
  await page.screenshot({ path: testInfo.outputPath('targets.png'), fullPage: true })
  for (const width of [768, 390, 320]) {
    await page.setViewportSize({ width, height: 980 })
    await targetList.getByRole('button', { name: 'Local', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Local', exact: true })).toBeVisible()
    await page.getByRole('navigation', { name: 'Breadcrumb', exact: true }).getByRole('button', { name: 'My files', exact: true }).click()
    await expect(targetList.getByRole('button')).toHaveCount(2)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 1440, height: 980 })
  await targetList.getByRole('button', { name: 'Archive', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Archive', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'archive-only.txt', exact: true })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Breadcrumb', exact: true }).locator('li')).toHaveText(['My files', 'Archive'])
  await expect(page.getByRole('button', { name: 'Upload files', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Parent folder', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'My files', exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Archive', exact: true })).toBeVisible()
  await page.goForward()
  await expect(page.getByRole('heading', { name: 'My files', exact: true })).toBeVisible()
  await page.goto('/#/files/' + disabledId)
  await expect(page.getByRole('status')).toContainText('This target is unavailable')
  await expect(targetList.getByRole('button', { name: 'Local', exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Main', exact: true }).getByRole('button', { name: 'My files', exact: true }).click()
  await targetList.getByRole('button', { name: 'Local', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Local', exact: true })).toBeVisible()
  await page.keyboard.press('Control+ArrowUp')
  await expect(page.getByRole('heading', { name: 'My files', exact: true })).toBeVisible()
  await openLocalFolder(page, '')
  await expect(page.getByRole('navigation', { name: 'Breadcrumb', exact: true }).locator('li')).toHaveText(['My files', 'Local'])
  await page.getByRole('button', { name: 'New folder', exact: true }).click()
  for (const invalid of ['..', '文'.repeat(86), 'bad\\name']) {
    await page.getByLabel('Folder name').fill(invalid)
    await expect(page.getByLabel('Folder name')).toHaveAttribute('aria-invalid', 'true')
    await expect(page.getByRole('button', { name: 'Create folder', exact: true })).toBeDisabled()
  }
  await page.getByLabel('Folder name').fill('Team documents')
  await page.getByRole('button', { name: 'Create folder', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Team documents', exact: true })).toBeVisible()
  const rootListing = (url: URL) => url.pathname.endsWith('/files') && url.searchParams.get('path') === '/'
  let releaseRoot: (() => Promise<void>) | undefined
  let capturedRoot!: () => void
  const rootCaptured = new Promise<void>(resolve => { capturedRoot = resolve })
  await page.route(rootListing, async route => {
    const response = await route.fetch()
    releaseRoot = () => route.fulfill({ response })
    capturedRoot()
  })
  await page.getByRole('button', { name: 'Refresh files', exact: true }).click()
  await rootCaptured
  await page.getByRole('button', { name: 'Team documents', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'This folder is empty', exact: true })).toBeVisible()
  await releaseRoot!()
  await expect(page.getByRole('button', { name: 'Refresh files', exact: true }).locator('svg')).not.toHaveClass(/spin/)
  await expect(page.getByRole('heading', { name: 'This folder is empty', exact: true })).toBeVisible()
  await page.unroute(rootListing)
  await page.getByRole('button', { name: 'Upload files', exact: true }).click()
  await page.getByLabel('Connections per chunk').selectOption('4')
  const content = Buffer.from('A file uploaded, hashed, and verified through the real browser.\n'.repeat(500))
  await page.locator('input[type=file][multiple]').setInputFiles({ name: 'project-notes.md', mimeType: 'text/markdown', buffer: content })
  await expect(page.locator('.transfer-row').filter({ hasText: 'project-notes.md' }).getByText('Complete', { exact: true })).toBeVisible({ timeout: 30_000 })
  await openLocalFolder(page)
  await expect(page.getByRole('button', { name: 'project-notes.md', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'project-notes.md', exact: true }).click()
  await expect(page.locator('.text-preview')).toContainText('verified through the real browser')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download', exact: true }).click()
  const download = await downloadPromise
  const downloadedPath = await download.path()
  expect(await readFile(downloadedPath!)).toEqual(content)
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Grid view' }).click()
  await page.screenshot({ path: testInfo.outputPath('files-grid.png'), fullPage: true })
  await page.getByRole('button', { name: 'List view' }).click()
  await page.screenshot({ path: testInfo.outputPath('files-list.png'), fullPage: true })

  await mkdir(join(process.env.FB_E2E_ROOT!, 'files', 'Team documents', 'empty'), { recursive: true })
  await page.getByRole('button', { name: 'Refresh files' }).click()
  await page.getByRole('button', { name: 'empty', exact: true }).click()
  const crumbs = page.getByRole('navigation', { name: 'Breadcrumb', exact: true })
  await expect(crumbs.locator('li')).toHaveText(['My files', 'Local', 'Team documents', 'empty'])
  await crumbs.getByRole('button', { name: 'Team documents', exact: true }).click()
  await expect(page.getByRole('button', { name: 'project-notes.md', exact: true })).toBeVisible()
  const archivePromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download folder', exact: true }).click()
  const folderDownload = await archivePromise
  expect(folderDownload.suggestedFilename()).toBe('Team documents.tar')
  const folderArchive = await tarContents((await folderDownload.path())!)
  expect(folderArchive.get('project-notes.md')).toEqual(content)
  expect(folderArchive.has('empty/')).toBe(true)
  await page.getByLabel('Select empty', { exact: true }).check()
  await page.getByLabel('Select project-notes.md', { exact: true }).check()
  const mixedPromise = page.waitForEvent('download')
  await page.locator('.selection-bar').getByRole('button', { name: 'Download', exact: true }).click()
  const mixedDownload = await mixedPromise
  expect(mixedDownload.suggestedFilename()).toBe('selection.tar')
  const mixedArchive = await tarContents((await mixedDownload.path())!)
  expect(mixedArchive.get('project-notes.md')).toEqual(content)
  expect(mixedArchive.has('empty/')).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('archive-selection.png'), fullPage: true })
  await page.keyboard.press('Control+ArrowUp')
  await expect(page.getByRole('heading', { name: 'Local', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Team documents', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Team documents', exact: true })).toBeVisible()
  await page.keyboard.press('Meta+ArrowUp')
  await expect(page.getByRole('heading', { name: 'Local', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Team documents', exact: true }).click()

  const testRoot = process.env.FB_E2E_ROOT!
  await mkdir(join(testRoot, 'source'), { recursive: true })
  const largePath = join(testRoot, 'source', 'large-source.bin')
  const chunkSize = 100 * 1024 * 1024
  const file = await open(largePath, 'w')
  await file.truncate(chunkSize + 1024 * 1024)
  await file.close()
  let interrupted = false
  await page.route('**/api/uploads/*/chunks/1/start', async route => {
    interrupted = true
    await route.abort('failed')
  })
  await page.getByRole('button', { name: 'Upload files', exact: true }).click()
  await page.locator('input[type=file][multiple]').setInputFiles(largePath)
  await expect.poll(() => interrupted, { timeout: 45_000 }).toBe(true)
  await expect(page.locator('.transfer-row').filter({ hasText: 'large-source.bin' })).toContainText('100 MiB verified')
  await openLocalFolder(page)
  const pendingRow = page.getByRole('row').filter({ hasText: 'large-source.bin.uploading' })
  await expect(pendingRow.getByText('Uploading', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Select large-source.bin.uploading')).toBeDisabled()
  await page.getByRole('button', { name: 'large-source.bin.uploading', exact: true }).click()
  await expect(page.getByText('This file is still uploading.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Download', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Rename', exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('uploading-details.png'), fullPage: true })
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.screenshot({ path: testInfo.outputPath('uploading-file.png'), fullPage: true })
  await page.reload()
  await page.unroute('**/api/uploads/*/chunks/1/start')
  await page.getByRole('button', { name: 'Transfers', exact: false }).first().click()
  const transfer = page.locator('.transfer-row').filter({ hasText: 'large-source.bin' })
  await expect(transfer).toContainText('Ready to resume')
  await transfer.getByRole('button', { name: 'Select file' }).click()
  await page.locator('input[type=file]:not([multiple])').setInputFiles(largePath)
  await expect(transfer.getByText('Complete', { exact: true })).toBeVisible({ timeout: 45_000 })
  const result = await readFile(join(testRoot, 'files', 'Team documents', 'large-source.bin'))
  expect(result.length).toBe(chunkSize + 1024 * 1024)
  expect(createHash('sha256').update(result).digest('hex')).toBe(createHash('sha256').update(await readFile(largePath)).digest('hex'))
  await page.screenshot({ path: testInfo.outputPath('transfers.png'), fullPage: true })
  await openLocalFolder(page)
  await expect(page.getByRole('button', { name: 'large-source.bin', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'large-source.bin.uploading', exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: 'People & access' }).click()
  await page.getByRole('button', { name: 'Add a person' }).click()
  await page.getByLabel('Username', { exact: true }).fill('alex')
  await page.getByLabel('Password', { exact: true }).fill('member-test-password-123')
  await page.locator('.grant-card').filter({hasText:'Local'}).locator('input[type=checkbox]').first().check()
  await page.getByLabel('Local home folder').fill('/Team documents')
  await page.getByRole('button', { name: 'Read only', exact: true }).click()
  await page.getByRole('button', { name: 'Add person', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: 'alex' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('people.png'), fullPage: true })
  await page.getByRole('button', { name: 'Edit alex' }).click()
  await expect(page.getByLabel('Upload', { exact: false })).not.toBeChecked()
  await page.getByRole('button', { name: 'Close dialog' }).click()
  const member = await context.browser()!.newContext()
  const memberPage = await member.newPage()
  await memberPage.goto('http://127.0.0.1:3217/')
  await memberPage.getByLabel('Username', { exact: true }).fill('alex')
  await memberPage.getByLabel('Password', { exact: true }).fill('member-test-password-123')
  await memberPage.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(memberPage.getByRole('heading', { name: 'My files', exact: true })).toBeVisible()
  const memberTargets = memberPage.getByRole('list', { name: 'Storage targets', exact: true })
  await expect(memberTargets.getByRole('button')).toHaveCount(1)
  await expect(memberTargets.getByRole('button', { name: 'Archive', exact: true })).toHaveCount(0)
  await memberTargets.getByRole('button', { name: 'Local', exact: true }).click()
  await expect(memberPage.getByRole('button', { name: 'project-notes.md', exact: true })).toBeVisible()
  await expect(memberPage.getByRole('navigation', { name: 'Breadcrumb', exact: true }).locator('li')).toHaveText(['My files', 'Local'])
  await expect(memberPage.getByRole('button', { name: 'Upload files', exact: true })).toHaveCount(0)
  await expect(memberPage.getByRole('button', { name: 'People & access' })).toHaveCount(0)
  await memberPage.getByRole('button', { name: 'Account settings', exact: true }).click()
  await page.getByRole('button', { name: 'Edit alex' }).click()
  await page.getByLabel('Disable this account').check()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await memberPage.getByRole('button', { name: 'My files', exact: true }).first().click()
  await expect(memberPage.getByRole('heading', { name: 'Good to see you again.' })).toBeVisible()
  await member.close()
  const emptyUser = await context.request.post('/api/admin/users', { headers, data: { username: 'no-storage', password: 'no-storage-password-123', role: 'user', grants: [] } })
  expect(emptyUser.status()).toBe(201)
  const emptyContext = await context.browser()!.newContext()
  const emptyPage = await emptyContext.newPage()
  await emptyPage.goto('http://127.0.0.1:3217/')
  await emptyPage.getByLabel('Username', { exact: true }).fill('no-storage')
  await emptyPage.getByLabel('Password', { exact: true }).fill('no-storage-password-123')
  await emptyPage.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(emptyPage.getByRole('heading', { name: 'My files', exact: true })).toBeVisible()
  await expect(emptyPage.getByRole('heading', { name: 'No storage targets', exact: true })).toBeVisible()
  await expect(emptyPage.getByRole('button', { name: 'Add a target', exact: true })).toHaveCount(0)
  await emptyContext.close()
  await page.getByRole('button', { name: 'Activity', exact: true }).click()
  await expect(page.locator('.activity-list')).toContainText('finished an upload')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('group', { name: 'Theme', exact: true }).getByRole('button', { name: 'Dark', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('group', { name: 'Density', exact: true }).getByRole('button', { name: 'Comfortable', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-density', 'comfortable')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('html')).toHaveAttribute('data-density', 'comfortable')
  await page.getByRole('group', { name: 'Theme', exact: true }).getByRole('button', { name: 'Light', exact: true }).click()
  await page.getByRole('group', { name: 'Density', exact: true }).getByRole('button', { name: 'Compact', exact: true }).click()
  await expect(page.getByText('100 MiB', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'My files', exact: true }).first().click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('mobile-targets.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('list', { name: 'Storage targets', exact: true }).getByRole('button', { name: 'Local', exact: true }).click()
  await page.getByRole('button', { name: 'Team documents', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'Breadcrumb', exact: true }).locator('li')).toHaveText(['My files', 'Local', 'Team documents'])
  await page.screenshot({ path: testInfo.outputPath('mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.keyboard.press('Control+k')
  await page.getByLabel('Command', { exact: true }).fill('My files')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'My files', exact: true })).toBeVisible()
  await openLocalFolder(page)
  await page.keyboard.press('g')
  await page.keyboard.press('f')
  await expect(page.getByRole('heading', { name: 'My files', exact: true })).toBeVisible()
  expect(pageErrors).toEqual([])
  await writeFile(testInfo.outputPath('validation.txt'), 'Target hierarchy, breadcrumbs, target visibility, empty access, browser history, scoped users, text preview, byte-identical download, streamed folder and mixed archives, parent shortcuts, SHA-256 worker, 101 MiB upload, and reload resume verified.\n')
})
