import { test, expect } from '@playwright/test'
import { createHash } from 'node:crypto'
import { mkdir, open, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

test('setup, file operations, worker hashing, reload resume, scoped users, and mobile layout', async ({ page, context }, testInfo) => {
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Make yourself at home.' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('setup.png'), fullPage: true })
  await page.getByLabel('Workspace name').fill('Filebrowser')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByLabel('Username', { exact: true }).fill('admin')
  await page.getByLabel('Password', { exact: true }).fill('browser-test-password-123')
  await page.getByLabel('Confirm password').fill('browser-test-password-123')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Create workspace', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'All files.' })).toBeVisible()
  await page.getByRole('button', { name: 'New folder', exact: true }).click()
  await page.getByLabel('Folder name').fill('Team documents')
  await page.getByRole('button', { name: 'Create folder', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Team documents', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Team documents', exact: true }).click()
  await page.getByRole('button', { name: 'Upload files', exact: true }).click()
  await page.getByLabel('Connections per chunk').selectOption('4')
  const content = Buffer.from('A file uploaded, hashed, and verified through the real browser.\n'.repeat(500))
  await page.locator('input[type=file][multiple]').setInputFiles({ name: 'project-notes.md', mimeType: 'text/markdown', buffer: content })
  await expect(page.locator('.transfer-row').filter({ hasText: 'project-notes.md' }).getByText('Complete', { exact: true })).toBeVisible({ timeout: 30_000 })
  await page.getByRole('button', { name: 'My files', exact: true }).first().click()
  await expect(page.getByRole('button', { name: 'project-notes.md', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'project-notes.md', exact: true }).click()
  await page.getByRole('button', { name: 'Preview', exact: true }).click()
  await expect(page.locator('.text-preview')).toContainText('verified through the real browser')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download', exact: true }).click()
  const download = await downloadPromise
  const downloadedPath = await download.path()
  expect(await readFile(downloadedPath!)).toEqual(content)
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Grid view' }).click()
  await page.screenshot({ path: testInfo.outputPath('files-grid.png'), fullPage: true })
  await page.getByRole('button', { name: 'List view' }).click()
  await page.screenshot({ path: testInfo.outputPath('files-list.png'), fullPage: true })

  const testRoot = process.env.FB_E2E_ROOT!
  await mkdir(join(testRoot, 'source'), { recursive: true })
  const largePath = join(testRoot, 'source', 'large-source.bin')
  const chunkSize = 100 * 1024 * 1024
  const file = await open(largePath, 'w')
  await file.truncate(chunkSize + 1024 * 1024)
  await file.close()
  let interrupted = false
  await page.route('**/api/uploads/*/chunks/1/start', async route => {
    interrupted = true
    await route.abort('failed')
  })
  await page.getByRole('button', { name: 'Upload files', exact: true }).click()
  await page.locator('input[type=file][multiple]').setInputFiles(largePath)
  await expect.poll(() => interrupted, { timeout: 45_000 }).toBe(true)
  await expect(page.locator('.transfer-row').filter({ hasText: 'large-source.bin' })).toContainText('100 MiB verified')
  await page.getByRole('button', { name: 'My files', exact: true }).first().click()
  const pendingRow = page.getByRole('row').filter({ hasText: 'large-source.bin.uploading' })
  await expect(pendingRow.getByText('Uploading', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Select large-source.bin.uploading')).toBeDisabled()
  await page.getByRole('button', { name: 'large-source.bin.uploading', exact: true }).click()
  await expect(page.getByText('This file is still uploading.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Download', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Rename', exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('uploading-details.png'), fullPage: true })
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.screenshot({ path: testInfo.outputPath('uploading-file.png'), fullPage: true })
  await page.reload()
  await page.unroute('**/api/uploads/*/chunks/1/start')
  await page.getByRole('button', { name: 'Transfers', exact: false }).first().click()
  const transfer = page.locator('.transfer-row').filter({ hasText: 'large-source.bin' })
  await expect(transfer).toContainText('Ready to resume')
  await transfer.getByRole('button', { name: 'Select file' }).click()
  await page.locator('input[type=file]:not([multiple])').setInputFiles(largePath)
  await expect(transfer.getByText('Complete', { exact: true })).toBeVisible({ timeout: 45_000 })
  const result = await readFile(join(testRoot, 'files', 'Team documents', 'large-source.bin'))
  expect(result.length).toBe(chunkSize + 1024 * 1024)
  expect(createHash('sha256').update(result).digest('hex')).toBe(createHash('sha256').update(await readFile(largePath)).digest('hex'))
  await page.screenshot({ path: testInfo.outputPath('transfers.png'), fullPage: true })
  await page.getByRole('button', { name: 'My files', exact: true }).first().click()
  await page.getByRole('button', { name: 'Team documents', exact: true }).click()
  await expect(page.getByRole('button', { name: 'large-source.bin', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'large-source.bin.uploading', exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: 'People & access' }).click()
  await page.getByRole('button', { name: 'Add a person' }).click()
  await page.getByLabel('Username', { exact: true }).fill('alex')
  await page.getByLabel('Password', { exact: true }).fill('member-test-password-123')
  await page.getByLabel('Home folder').fill('/Team documents')
  await page.getByRole('button', { name: 'Read only', exact: true }).click()
  await page.getByRole('button', { name: 'Add person', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: 'alex' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('people.png'), fullPage: true })
  await page.getByRole('button', { name: 'Edit alex' }).click()
  await expect(page.getByLabel('Upload', { exact: false })).not.toBeChecked()
  await page.getByRole('button', { name: 'Close dialog' }).click()
  const member = await context.browser()!.newContext()
  const memberPage = await member.newPage()
  await memberPage.goto('http://127.0.0.1:3217/')
  await memberPage.getByLabel('Username', { exact: true }).fill('alex')
  await memberPage.getByLabel('Password', { exact: true }).fill('member-test-password-123')
  await memberPage.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(memberPage.getByRole('button', { name: 'project-notes.md', exact: true })).toBeVisible()
  await expect(memberPage.getByRole('button', { name: 'Upload files', exact: true })).toHaveCount(0)
  await expect(memberPage.getByRole('button', { name: 'People & access' })).toHaveCount(0)
  await memberPage.getByRole('button', { name: 'Account settings', exact: true }).click()
  await page.getByRole('button', { name: 'Edit alex' }).click()
  await page.getByLabel('Disable this account').check()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await memberPage.getByRole('button', { name: 'My files', exact: true }).first().click()
  await expect(memberPage.getByRole('heading', { name: 'Good to see you again.' })).toBeVisible()
  await member.close()
  await page.getByRole('button', { name: 'Activity', exact: true }).click()
  await expect(page.locator('.activity-list')).toContainText('finished an upload')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(page.getByText('100 MiB', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'My files', exact: true }).first().click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(pageErrors).toEqual([])
  await writeFile(testInfo.outputPath('validation.txt'), 'Setup, scoped users, text preview, byte-identical download, SHA-256 worker, 101 MiB upload, and reload resume verified.\n')
})
